// Generated by `supabase gen types typescript --linked > src/types/database.ts`
// Run that command after `supabase db push` to refresh.
// This stub keeps TypeScript happy until you generate real types.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = "farmer" | "admin";
export type Disease = "rice_blast" | "bacterial_leaf_blight" | "tungro";
export type Severity = "low" | "medium" | "high";
export type ScanStatus = "pending" | "processing" | "completed";
export type Delivery = "queued" | "sent" | "failed";
export type AdvisoryState = "draft" | "approved" | "sent";

export interface Profile {
  id: string;
  full_name: string | null;
  phone: string;
  role: UserRole;
  province: string | null;
  municipality: string | null;
  barangay: string | null;
  farm_size_ha: number | null;
  is_active: boolean;
  created_at: string;
}

export interface DroneScan {
  id: string;
  admin_id: string;
  scan_name: string;
  source_type: string | null;
  stored_path: string | null;
  captured_at: string | null;
  processed_at: string | null;
  status: ScanStatus;
  created_at: string;
}

export interface DiseaseDetection {
  id: string;
  scan_id: string;
  farmer_id: string | null;
  disease: Disease;
  severity: Severity;
  lat: number;
  lng: number;
  location_text: string | null;
  confidence_score: number | null;
  affected_area_pct: number | null;
  bbox_json: Json | null;
  image_url: string | null;
  created_at: string;
}

export interface Advisory {
  id: string;
  detection_id: string | null;
  farmer_id: string | null;
  admin_id: string;
  disease: Disease;
  severity: Severity;
  advice_text: string | null;
  sms_text: string | null;
  ai_generated: boolean;
  ai_model: string | null;
  state: AdvisoryState;
  sms_status: Delivery | null;
  sms_sent_at: string | null;
  sms_error: string | null;
  created_at: string;
  updated_at: string;
}

export interface NotificationPreferences {
  farmer_id: string;
  sms_enabled: boolean;
  critical_alerts: boolean;
  weekly_summary: boolean;
  updated_at: string;
}

export interface Database {
  public: {
    Tables: {
      profiles: { Row: Profile; Insert: Partial<Profile>; Update: Partial<Profile> };
      drone_scans: { Row: DroneScan; Insert: Partial<DroneScan>; Update: Partial<DroneScan> };
      disease_detections: { Row: DiseaseDetection; Insert: Partial<DiseaseDetection>; Update: Partial<DiseaseDetection> };
      advisories: { Row: Advisory; Insert: Partial<Advisory>; Update: Partial<Advisory> };
      notification_preferences: {
        Row: NotificationPreferences;
        Insert: Partial<NotificationPreferences>;
        Update: Partial<NotificationPreferences>;
      };
    };
    Enums: {
      user_role: UserRole;
      disease: Disease;
      severity: Severity;
      scan_status: ScanStatus;
      delivery: Delivery;
      advisory_state: AdvisoryState;
    };
  };
}
