import type { OperationsData } from "./domain";
// Isolated, synthetic workflow fixtures. Never training evidence or live field reports.
export const sampleData: OperationsData = {
  surveys: [
    {
      id: "demo-flight-01",
      name: "Santa Maria · North fields",
      location: "Santa Maria, Isabela",
      captured_at: "2026-09-06T00:30:00Z",
      camera: "DJI photo upload",
      status: "Needs review",
      photos: 24,
      severity: "not_calibrated",
      lat: 17.46,
      lng: 121.749,
      note: "Illustrative survey. Historical overlay shown for interface review only.",
    },
    {
      id: "demo-flight-02",
      name: "Cabagan · Riverside fields",
      location: "Cabagan, Isabela",
      captured_at: "2026-09-06T01:10:00Z",
      camera: "DJI photo upload",
      status: "Queued",
      photos: 18,
      severity: "unknown",
      lat: 17.427,
      lng: 121.772,
    },
    {
      id: "demo-flight-03",
      name: "Tumauini · East fields",
      location: "Tumauini, Isabela",
      captured_at: "2026-09-05T23:10:00Z",
      camera: "DJI photo upload",
      status: "Reviewed",
      photos: 12,
      severity: "low",
      lat: 17.298,
      lng: 121.808,
    },
    {
      id: "demo-flight-04",
      name: "Ilagan · Follow-up",
      location: "Ilagan, Isabela",
      captured_at: "2026-09-05T00:30:00Z",
      camera: "DJI photo upload",
      status: "Needs review",
      photos: 16,
      severity: "high",
      lat: 17.148,
      lng: 121.89,
    },
  ],
  bulletins: [
    {
      id: "sample-blb",
      slug: "sample-blb-field-advisory",
      title: "May pagbabago ba sa kulay ng mga dahon?",
      location: "Santa Maria, Isabela",
      disease: "BLB",
      severity: "not_calibrated",
      body: "Halimbawang advisory lamang. Ang paninilaw at pagkatuyo ng dahon ay nangangailangan ng pagsusuri sa bukid. Hindi sapat ang kulay o larawan para makumpirma ang BLB.",
      action:
        "Suriin ang mga apektadong dahon at kumonsulta sa municipal agriculture office bago magpasya sa paggamot. Magdala ng malinaw na larawan at sample kung hinihingi ng specialist.",
      date: "2026-09-06",
      status: "draft",
      image: "/evidence/tiled-4k-smoke-preview.jpg",
      reviewer: null,
      sample: true,
      lat: 17.46,
      lng: 121.749,
    },
    {
      id: "sample-blast",
      slug: "sample-rice-blast-field-guide",
      title: "Kilalanin at ipasuri ang posibleng Brown Spot",
      location: "Region II · Gabay sa pagsusuri",
      disease: "Brown Spot",
      severity: "not_calibrated",
      body: "Hindi lahat ng brown na bahagi ay Brown Spot. Ipa-review ang buong affected leaf at mga nakikitang lesion sa agriculture specialist; iwasang magbigay ng diagnosis mula sa kulay lamang.",
      action:
        "Kumuha ng malinaw na close-up at mas malawak na larawan ng palayan. Itala ang petsa at lokasyon para sa field verification.",
      date: "2026-09-05",
      status: "draft",
      image: "/images/rice-blast.webp",
      reviewer: null,
      sample: true,
      lat: 17.298,
      lng: 121.808,
    },
  ],
  contacts: [
    {
      id: "demo-contact-1",
      name: "Sample farmer A",
      phone: "+639000000001",
      location: "Santa Maria, Isabela",
      consent: true,
      verified: true,
      farms: [{ lat: 17.461, lng: 121.75 }],
    },
    {
      id: "demo-contact-2",
      name: "Sample farmer B",
      phone: "+639000000002",
      location: "Cabagan, Isabela",
      consent: false,
      verified: false,
      farms: [],
    },
  ],
  campaigns: [],
  assets: [],
  jobs: [],
  providers: {
    drive: "configuration_required",
    kaggle: "configuration_required",
    sms: "configuration_required",
    advisory: "configuration_required",
  },
  models: [],
};
